services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="postgresql://postgres:mysecretpassword@postgres:5432/docs"
      - MINIO_ENDPOINT="http://redis:9000"
      - MINIO_ACCESS_KEY="my_access_key"
      - MINIO_SECRET_KEY="my_secret_key"
    networks:
      - minio-services
  app-migrate-deploy:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: bun x prisma migrate deploy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="postgresql://postgres:mysecretpassword@postgres:5432/docs"
      - MINIO_ENDPOINT="http://redis:9000"
      - MINIO_ACCESS_KEY="my_access_key"
      - MINIO_SECRET_KEY="my_secret_key"
    networks:
      - minio-services

networks:
  minio-services:
    external: true
